data:
  train_files: hiyouga/math12k@train
  val_files: hiyouga/math12k@test
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 3072
  max_response_length: 2048
  rollout_batch_size: 16
  pr_batch_size: 32
  val_batch_size: 512
  format_prompt: ./examples/format_prompt/avt_format.jinja
  override_chat_template: null
  shuffle: true
  seed: 1
  max_pixels: 1048576 # 1024 * 1024, reduce vision tokens
  min_pixels: 262144  # 512 * 512
  filter_overlong_and_invalid_prompts: true
  train_max_samples: 128
  val_max_samples: 32

algorithm:
  adv_estimator: grpo
  disable_kl: false
  use_kl_loss: true
  kl_penalty: low_var_kl
  kl_coef: 1.0e-2

worker:
  actor:
    global_batch_size: 8
    micro_batch_size_per_device_for_update: 1
    micro_batch_size_per_device_for_experience: 8
    max_grad_norm: 1.0
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: /data1/qxwang/checkpoints/Qwen2.5-VL-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
      freeze_vision_tower: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      strategy: adamw_bf16
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true
    offload:
      offload_params: true
      offload_optimizer: true

  rollout:
    n: 2
    temperature: 1.0
    top_p: 0.99
    max_num_seqs: 128
    gpu_memory_utilization: 0.6
    enforce_eager: false
    enable_chunked_prefill: true
    tensor_parallel_size: 1
    limit_images: 4
    sampling_strategy: mc
    repetition_penalty: 1.0
    val_override_config:
      temperature: 0.1
      n: 1

  ref:
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: true
      enable_rank0_init: true
    offload:
      offload_params: false

  reward:
    reward_type: batch
    reward_function: ./examples/reward_function/avt_reward_function.py:compute_score

  rule_based_judge:
    judge_type: single
    judge_function: ./examples/reward_function/avt_reward_function.py:rule_then_api_batch_judge
    api_name: gemini-2.5-pro
    api_kwargs:
      temperature: 0.1

trainer:
  total_epochs: 1
  max_steps: null
  project_name: easy_r1
  experiment_name: qwen2_5_7b_math_grpo_safe
  logger: ["console", "wandb"]
  nnodes: 1
  n_gpus_per_node: 4
  val_freq: 5
  val_before_train: true
  val_only: false
  val_generations_to_log: 20
  save_freq: 50
  save_limit: 10
  save_checkpoint_path: null
  load_checkpoint_path: null
